apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNoExternalServices
metadata:
  name: no-internet-services
spec:
  enforcementAction: deny
  match:
    namespaces:
      - hello-namespace
  parameters:
    internalCIDRs: [] 

